#!name=odlist
#!desc=不白，不黑 odlist
#!src=https://raw.githubusercontent.com/
[MITM]
hostname = %APPEND% *.cloudvideocdn.taobao.com, *.alicdn.com, 

[Rule]
#0 淘宝视频
# URL-REGEX,^https?:\/\/.*cloudvideocdn\.taobao\.com\/.*\.mp4.*,REJECT-200
DOMAIN-SUFFIX,cloudvideocdn.taobao.com,REJECT-200

#0 淘宝其他
#DOMAIN-SUFFIX,acs.m.taobao.com,REJECT-200
#DOMAIN-SUFFIX,agoo-report.m.taobao.com,REJECT-200
#DOMAIN-SUFFIX,xjp-jmacs.m.taobao.com,REJECT-200
#DOMAIN-SUFFIX,adashx4ae.ut.taobao.com,REJECT-200
#DOMAIN-SUFFIX,audid-api-sg.taobao.com,REJECT-200

#DOMAIN-SUFFIX,guide-acs.m.taobao.com,REJECT-200
DOMAIN-SUFFIX,umengacs.m.taobao.com,REJECT-200
#DOMAIN-SUFFIX,amdcopen.m.taobao.com,REJECT-200
DOMAIN-SUFFIX,umengjmacs.m.taobao.com,REJECT-200
#DOMAIN-SUFFIX,amdc.m.taobao.com,REJECT-200
#DOMAIN-SUFFIX,xjp-msgacs.m.taobao.com,REJECT-200
DOMAIN-SUFFIX,adashx4sg.ut.taobao.com,REJECT-200
#DOMAIN-SUFFIX,accscdn.m.taobao.com,REJECT-200
#DOMAIN-SUFFIX,trade-acs.m.taobao.com,REJECT-200
#DOMAIN-SUFFIX,ip.taobao.com,REJECT-200

#1. 
#DOMAIN,steambroadcast.akamaized.net

#2
DOMAIN-SUFFIX,apple.com,PROXY
HOST-SUFFIX,icloud.com,PROXY
DOMAIN-SUFFIX,icloud-content.com，PROXY

DOMAIN-SUFFIX,ulogs.umengcloud.com,REJECT-200
DOMAIN-SUFFIX,gss3.bdstatic.com,REJECT-200


#3
HOST-SUFFIX,freezhihu.org,PROXY
DOMAIN-SUFFIX,freeweibo.com,PROXY
#DOMAIN-SUFFIX,ip138.com,PROXY

#4
DOMAIN-SUFFIX,bellesa.co,PROXY
DOMAIN-SUFFIX,loader.to,PROXY

